name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy matplotlib ruff  # Add any other dependencies here

    - name: Check code formatting
      run: ruff format --check

    - name: Run tests
      run: python -m unittest discover -s . -p 'test_main.py'